# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    # Configure App Store Connect API
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: true
    )
    
    # Increment build number
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
    )
    
    # Build the app
    build_ios_app(
      workspace: "carpeApp.xcworkspace",
      scheme: "carpeApp",
      export_method: "app-store",
      clean: true,
      archive_path: "./builds/carpeApp.xcarchive",
      output_directory: "./builds",
      output_name: "carpeApp.ipa"
    )
    
    # Upload to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false
    )
  end

  desc "Build for App Store"
  lane :release do
    # Configure App Store Connect API
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: true
    )
    
    # Increment version number
    increment_version_number(
      version_number: latest_testflight_build_number + 1,
    )
    
    # Build the app
    build_ios_app(
      workspace: "carpeApp.xcworkspace",
      scheme: "carpeApp",
      export_method: "app-store",
      clean: true,
      archive_path: "./builds/carpeApp.xcarchive",
      output_directory: "./builds",
      output_name: "carpeApp.ipa"
    )
    
    # Upload to App Store Connect
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: false,
      automatic_release: false
    )
  end

  desc "Run tests"
  lane :test do
    scan(
      workspace: "carpeApp.xcworkspace",
      scheme: "carpeApp",
      device: "iPhone 15"
    )
  end

  desc "Clean build artifacts"
  lane :clean do
    clean_build_artifacts
    sh "rm -rf ./builds"
    sh "rm -rf ~/Library/Developer/Xcode/DerivedData"
  end
end 